version: "3.10"
services:
  sim:
    build:
      context: ./
      dockerfile: ./docker/sim.Dockerfile
    volumes:
      - ./lab4:/home/default-user/ws/
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:1
      - TURTLEBOT3_MODEL=burger
    runtime: nvidia
    command: /idle.bash
